export const GETCOURSESTARTED = "COURSES/GETCOURSESTARTED";
export const GETCOURSESUCCESS = "COURSES/GETCOURSESUCCESS";
export const GETCOURSEFAILED = "COURSES/GETCOURSEFAILED";

export const SETCURRENTPAGE = "COURSES/SETCURRENTPAGE";

export const SUBCOURSESSTARTED = "COURSES/SUBCOURSESSTARTED";
export const SUBCOURSESSUCCESS = "COURSES/SUBCOURSESSUCCESS";
export const SUBCOURSESFAILED = "COURSES/SUBCOURSESFAILED";

export const UNSUBCOURSESSTARTED = "COURSES/SUBCOURSESSTARTED";
export const UNSUBCOURSESSUCCESS = "COURSES/SUBCOURSESSUCCESS";
export const UNSUBCOURSESFAILED = "COURSES/SUBCOURSESFAILED";

export const GETPROFILESTARTED = "STUDENTS/GETPROFILESTARTED";
export const GETPROFILESUCCESS = "STUDENTS/GETPROFILESUCCESS";
export const GETPROFILEFAILED = "STUDENTS/GETPROFILEFAILED";