export const GETCOURSESTARTED = "COURSES/GETCOURSESTARTED";
export const GETCOURSESUCCESS = "COURSES/GETCOURSESUCCESS";
export const GETCOURSEFAILED = "COURSES/GETCOURSEFAILED";

export const SETCURRENTPAGE = "COURSES/SETCURRENTPAGE";

export const ADDCOURSESSTARTED = "COURSES/ADDCOURSESSTARTED";
export const ADDCOURSESSUCCESS = "COURSES/ADDCOURSESSUCCESS";
export const ADDCOURSESFAILED = "COURSES/ADDCOURSESFAILED";