export const GETSTUDENTSTARTED = "student/GETSTUDENTSTARTED";
export const GETSTUDENTSUCCESS = "student/GETSTUDENTSUCCESS";
export const GETSTUDENTFAILED = "student/GETSTUDENTFAILED";

export const GETCOURSESTARTED = "student/GETSTUDENTSTARTED";
export const GETCOURSESUCCESS = "student/GETSTUDENTSUCCESS";
export const GETCOURSEFAILED = "student/GETSTUDENTFAILED";


export const SETCURRENTPAGE = "student/SETCURRENTPAGE";

export const EDITSTUDENTSTARTED = "student/EDITSTUDENTSTARTED";
export const EDITSTUDENTSUCCESS = "student/EDITSTUDENTSUCCESS";
export const EDITSTUDENTFAILED = "student/EDITSTUDENTFAILED";